name: mapping_stellar_surfaces
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl-service>=2.3.0
  - numpy>=1.19.2
  - openblas=0.3.6
  - pip>=20.3.3
  - python=3.7.3
  - scipy>=1.5.2
  - setuptools>=51.3.3
  - sympy>=1.7.1
  - tectonic>=0.1.12
  - pip:
    - arviz>=0.11.0
    - astropy>=4.2
    - corner>=2.1.0
    - dynesty>=1.0.1
    - emcee>=3.0.2
    - exoplanet>=0.4.3
    - healpy>=1.14.0
    - matplotlib>=3.3.3
    - nose>=1.3.7
    - parameterized>=0.8.1
    - pymc3==3.9.0
    - pymc3-ext==0.0.2
    - pytest>=6.2.1
    - pytest-dependency>=0.5.1
    - pytest-env>=0.6.2
    - git+git://github.com/rodluger/starry.git#master
    - git+git://github.com/rodluger/starry_process.git#v0.9.4
    - theano==1.0.5
    - tqdm>=4.56.0
    - xarray>=0.16.2
