name: JOSS
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  paper:
    runs-on: ubuntu-latest
    name: JOSS paper draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md
      - name: Push to GitHub
        run: |
          git checkout --orphan joss-pdf
          git rm -rf .
          git add -f joss/paper.pdf
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "building JOSS paper"
          git push -q -f https://github.com/$GITHUB_REPOSITORY joss-pdf
    
